### ISSUE TITLE
Question?

### ISSUE THREAD

**Issue by daneb** [robertsundstrom/HttpListener#1]
Good work! 
If I may ask, how is this different to Microsoft.AspNetCore.Server.Kestrel HTTP Listener?

**Comment by marinasundstrom** [comment]
@daneb I'm not into Kestrel and therefore I don't know the specific details of that project. My goal was to build an equivalent API surface to that of the HTTP Listener API in .NET Framework mainly for my own use.

**Comment by marinasundstrom** [comment]
@daneb forgot... thanks!
