### ISSUE TITLE
Relationship between response.WriteContentAsync() and response.Close()

### ISSUE THREAD

**Issue by williamsharkey** [robertsundstrom/HttpListener#2]
Hello Robert Sundstrom,

In the example on Github's readme, it sends a message using `response.WriteAsync`.

(Minor point: Has WriteAsync's name been changed to `WriteContentAsync`?)

Is the README code actually enough to send the message? I have a slightly modified version of this project, and I find that I need to call response.Close immediately following `response.WriteContentAsync`.

What is the relationship between these functions?

Thanks,
Wm

```
var listener = new HttpListener(IPAddress.Parse("127.0.0.1"), 8081);
try 
{
    listener.Request += async (sender, context) => {
        var request = context.Request;
        var response = context.Response;
        if(request.Method == HttpMethod.Get) 
        {
            await response.WriteAsync($"Hello from Server at: {DateTime.Now}\r\n");
        }
        else
        {
            response.MethodNotAllowed();
        }
    };
    listener.Start();

    Console.WriteLine("Press any key to exit.");
    Console.ReadKey();
}
catch(Exception exc) 
{
    Console.WriteLine(exc.ToString());
}
finally 
{
    listener.Close();
}
```

**Comment by marinasundstrom** [comment]
Hi. I'm sorry for not answering sooner. 

Your observations are correct. You have to Close the message in order for it to be sent. 

My bad for not adding it to the ReadMe.

**Comment by marinasundstrom** [comment]
I have updated the sample in the README. They are now reflecting the unit tests.
