### ISSUE TITLE
NuGet Feed dead?

### ISSUE THREAD

**Issue by lucaschimweg** [robertsundstrom/HttpListener#3]
Hey!
I think the NuGet-Feed is dead. When I open https://www.myget.org/F/portable-http-listener/api/v3/index.json (with a browser), it just says "Feed does not exist."... Is there any way to fix this?

**Comment by marinasundstrom** [comment]
@lucaschimweg Sorry for not answering sooner. 

The package is now in this feed:

```
https://www.myget.org/F/roberts-core-feed/api/v3/index.json.
```

**Comment by queequac** [comment]
Even though this issue is closed... also the "new" nuget feed seems to be outdated. Last publish date there is April 5th 2016, the repository has several commits up to November.

Any reason why the nuget package was not updated anymore?
